### ISSUE TITLE
Conversation Service Issues

### ISSUE THREAD

**Issue by d1brok** [IBM-Bluemix/cloudco-insurance#10]
i have deplyoed all API Services manually as documented. All Apps are running fine. nevertheless the conversation seems to have problems. ANA is telling me "I ran into an error. Could you please try again". This is independent of any message i enter into the dialogue.
Launching the conversation service directly from the Bluemix dashboard the conversation test seems to work fine.

Any idea?

**Comment by l2fprod** [comment]
@d1brok did you set the WORKSPACE_ID environment variable in the DEPLOY pipeline of the insurance-bot app?

**Comment by l2fprod** [comment]
Please reopen with more information.
