### ISSUE TITLE
Does not work with toolchain in Frankfurt

### ISSUE THREAD

**Issue by rmey** [IBM-Bluemix/cloudco-insurance#13]
Some URLs for the API Endpoints maybe different, I could not deploy it, Toolchain will contain no delivery stages in the delivery pipeline.

**Comment by VidyasagarMSC** [comment]
@rmey With the new changes in place. I tried to deploy the app to Germany and everything works as expected. Can you give I try and let me know if you face any issues?

**Comment by rmey** [comment]
Thank you for fixing that.
