### ISSUE TITLE
Reset password functionality and better error messages 

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/cloudco-insurance#8]
No way to rest my password if you forgot the pass. 
That is needed, tech seller reported that they cant login and the issue is that the error messages are not clear. 

We need following:
1) Add Rest Password functionality 
2) When creating an account, if user is already exist then better error message needs to be displayed.

**Comment by uwefassnacht** [comment]
@rvennam, you want to take it? I think Twana has a point here. 
1. Not sure if a "password reset" link is really required ... it's easy enough to create a new ID. Depends on the coding effort required.
2. But the error message should be improved

**Comment by l2fprod** [comment]
should be covered by #15

**Comment by l2fprod** [comment]
![image](https://user-images.githubusercontent.com/12746550/42635076-496f2400-85e5-11e8-87c7-d574f57e9608.png)
